version: '3.5'
networks:
  lan:
    name: 'lan'


services:
  server:
    container_name: 'server'
    image: 'server:testing'
    build:
      context: './server'
    networks:
      - 'lan'

  client:
    container_name: 'client'
    image: 'client:testing'
    build:
      context: './client'
    networks:
      - 'lan'
    depends_on:
      - 'server'